#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# MYXON WiFi Access Point setup — Orange Pi wlan0
#
# Назначение:
#   Поднять на wlan0 точку доступа, чтобы фермер/технарь подключился
#   телефоном и открыл Local Agent API (http://192.168.42.1:8765) без облака.
#
# Что настраивает:
#   • hostapd  — точка доступа WiFi (SSID, WPA2-PSK)
#   • dnsmasq  — DHCP для клиентов на wlan0 (не трогает eth0)
#   • wlan0    — статический IP 192.168.42.1
#   • systemd  — оба сервиса в автозапуск
#
# Использование:
#   sudo bash setup-wifi-ap.sh [SSID] [PASSPHRASE] [IFACE]
#
#   Параметры можно передать переменными среды:
#     AP_SSID=MYXON-Farm-001 AP_PASS=secret123 sudo bash setup-wifi-ap.sh
#
# По умолчанию:
#   SSID        = MYXON-Device
#   Passphrase  = myxon1234
#   Interface   = wlan0
#   AP IP       = 192.168.42.1/24
#   DHCP range  = 192.168.42.10 – 192.168.42.50
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

AP_SSID="${AP_SSID:-${1:-MYXON-Device}}"
AP_PASS="${AP_PASS:-${2:-myxon1234}}"
WIFI_IFACE="${WIFI_IFACE:-${3:-wlan0}}"
AP_IP="192.168.42.1"
AP_NETMASK="255.255.255.0"
AP_CIDR="192.168.42.0/24"
DHCP_START="192.168.42.10"
DHCP_END="192.168.42.50"
DHCP_LEASE="12h"

HOSTAPD_CONF="/etc/hostapd/myxon-ap.conf"
DNSMASQ_CONF="/etc/dnsmasq.d/myxon-wifi.conf"

log()  { echo -e "\033[1;32m▶ $*\033[0m"; }
warn() { echo -e "\033[1;33m⚠ $*\033[0m"; }
die()  { echo -e "\033[1;31m✖ $*\033[0m"; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root: sudo bash setup-wifi-ap.sh"

# ── Sanity checks ─────────────────────────────────────────────────────────────
log "Checking WiFi interface $WIFI_IFACE..."
if ! ip link show "$WIFI_IFACE" &>/dev/null; then
    die "Interface $WIFI_IFACE not found. Available interfaces: $(ip link show | awk -F': ' '/^[0-9]+:/{print $2}' | tr '\n' ' ')"
fi

# Check that iw/wireless tools exist and interface supports AP mode
if command -v iw &>/dev/null; then
    if iw phy "$(iw dev "$WIFI_IFACE" info 2>/dev/null | awk '/wiphy/{print "phy"$2}')" info 2>/dev/null | grep -q "AP"; then
        log "Interface supports AP mode ✓"
    else
        warn "Could not confirm AP mode support — proceeding anyway (check hostapd logs if it fails)"
    fi
fi

if [ "${#AP_PASS}" -lt 8 ]; then
    die "WiFi passphrase must be at least 8 characters"
fi

# ── 1. Install packages ───────────────────────────────────────────────────────
log "Installing hostapd and dnsmasq..."
apt-get update -q
apt-get install -y -q hostapd dnsmasq

# Mask the default dnsmasq service — we use a conf.d snippet, not the whole thing
# (dnsmasq may already manage eth0 DNS; we only add our WiFi DHCP config)

# ── 2. Static IP on wlan0 (via /etc/network/interfaces.d/) ───────────────────
log "Configuring static IP $AP_IP on $WIFI_IFACE..."
cat > "/etc/network/interfaces.d/myxon-$WIFI_IFACE" <<EOF
# MYXON WiFi AP — managed by setup-wifi-ap.sh
auto $WIFI_IFACE
iface $WIFI_IFACE inet static
    address $AP_IP
    netmask $AP_NETMASK
EOF

# Apply immediately (don't fail if already up)
ip addr flush dev "$WIFI_IFACE" 2>/dev/null || true
ip addr add "$AP_IP/24" dev "$WIFI_IFACE" 2>/dev/null || true
ip link set "$WIFI_IFACE" up

# ── 3. hostapd config ─────────────────────────────────────────────────────────
log "Writing hostapd config → $HOSTAPD_CONF..."
mkdir -p /etc/hostapd
cat > "$HOSTAPD_CONF" <<EOF
# MYXON WiFi AP — generated by setup-wifi-ap.sh
interface=$WIFI_IFACE
ssid=$AP_SSID

# 802.11n, 2.4 GHz
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1

# WPA2-PSK (AES)
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=$AP_PASS

# Isolate AP clients from each other (phones can't see each other)
ap_isolate=1

# SSID visible in scan
ignore_broadcast_ssid=0
EOF
chmod 600 "$HOSTAPD_CONF"

# Point the default hostapd daemon at our config
if [ -f /etc/default/hostapd ]; then
    sed -i "s|^#\?DAEMON_CONF=.*|DAEMON_CONF=\"$HOSTAPD_CONF\"|" /etc/default/hostapd
fi

# ── 4. systemd hostapd override (use our config, not the default) ─────────────
log "Configuring hostapd systemd unit..."
mkdir -p /etc/systemd/system/hostapd.service.d
cat > /etc/systemd/system/hostapd.service.d/myxon-ap.conf <<EOF
[Service]
ExecStart=
ExecStart=/usr/sbin/hostapd $HOSTAPD_CONF
EOF

# ── 5. dnsmasq DHCP for wlan0 ────────────────────────────────────────────────
log "Writing dnsmasq DHCP config → $DNSMASQ_CONF..."
cat > "$DNSMASQ_CONF" <<EOF
# MYXON WiFi DHCP — generated by setup-wifi-ap.sh
# Serves DHCP only on $WIFI_IFACE (does not affect eth0 or other interfaces)
interface=$WIFI_IFACE
bind-interfaces

# DHCP range and lease time
dhcp-range=$DHCP_START,$DHCP_END,$DHCP_LEASE

# Tell phones: gateway and DNS is the Orange Pi
dhcp-option=3,$AP_IP
dhcp-option=6,$AP_IP

# Simple DNS: resolve "myxon.local" to the Orange Pi IP
address=/myxon.local/$AP_IP
address=/myxon/$AP_IP
EOF

# ── 6. Enable and start services ──────────────────────────────────────────────
log "Enabling hostapd and dnsmasq..."
systemctl daemon-reload
systemctl unmask hostapd 2>/dev/null || true
systemctl enable hostapd dnsmasq

log "Starting services..."
systemctl restart hostapd || { warn "hostapd failed to start. Check: journalctl -u hostapd"; }
systemctl restart dnsmasq || { warn "dnsmasq failed to start. Check: journalctl -u dnsmasq"; }

# ── 7. Summary ────────────────────────────────────────────────────────────────
echo ""
log "WiFi AP configured!"
echo ""
echo "  ┌─────────────────────────────────────────────────────┐"
echo "  │  SSID        : $AP_SSID"
echo "  │  Passphrase  : $AP_PASS"
echo "  │  Interface   : $WIFI_IFACE"
echo "  │  Orange Pi   : http://$AP_IP:8765"
echo "  │  mDNS alias  : http://myxon.local:8765"
echo "  └─────────────────────────────────────────────────────┘"
echo ""
echo "  Farmer's phone: connect to \"$AP_SSID\" → open http://$AP_IP:8765"
echo ""
echo "  Check status:"
echo "    journalctl -u hostapd -f"
echo "    journalctl -u dnsmasq -f"
echo ""
echo "  To change SSID/password later, edit:"
echo "    $HOSTAPD_CONF"
echo "    systemctl restart hostapd"
